:sparkles:can now use multiple emojis

diff --git a/commit b/commit
--- a/commit
+++ b/commit
@@ -8,7 +8,7 @@ usage() {
         "-h or --help             : display this message"
         "-f or --feature          : new features"
         "-w or --work-in-progress : move stuff around (methods up or down, re-indent, PSR-12 ...)"
-        "-ui or --user-interface  : change user interface"
+        "-u or --user-interface  : change user interface"
         "-b or --bug              : fix bug"
         "-r or --refacto          : refacto"
         "-d or --documentation    : update documentation"
@@ -19,56 +19,90 @@ usage() {
     printf "  %s\n" "${documentation[@]}"
 }
 
-type=''
+preview=false
+type+=()
 arguments=()
 while [ "$#" -gt 0 ]; do
     case "$1" in
         "-h" | "--help")
             usage
             exit
-            ;;
+        ;;
         "--feature" | "-f")
-            type="sparkles"
-            ;;
+            type+=("sparkles")
+        ;;
         "--work-in-progress" | "-w")
-            type="construction"
-            ;;
-        "--user-interface" | "-ui")
-            type="lipstick"
-            ;;
+            type+=("construction")
+        ;;
+        "--user-interface" | "-u")
+            type+=("lipstick")
+        ;;
         "--bug" | "-b")
-            type="bug"
-            ;;
+            type+=("bug")
+        ;;
         "--refacto" | "-r")
-            type="art"
-            ;;
+            type+=("art")
+        ;;
         "--documentation" | "-d")
-            type="pencil"
-            ;;
+            type+=("pencil")
+        ;;
         "--init"|"-i")
-            type="tada"
-            ;;
+            type+=("tada")
+        ;;
         "--parser"|"-p")
-            type="alembic"
-            ;;
+            type+=("alembic")
+        ;;
+        "--preview")
+            preview=true
+        ;;
+        "--")
+            shift
+            arguments+=("$@")
+            set --
+            break;
+        ;;
+        --*)
+            echo "Unknown long option $1" >&2
+            exit 3
+        ;;
+        -*)
+            if [ "${#1}" -eq 1 ]; then
+                echo "Invalid token -" >&2
+                exit 1
+            fi
+            if [ "${#1}" -eq 2 ]; then
+                echo "unknown option $1" >&2
+                exit 2
+            fi
+            first=${1:1:1}
+            rest=${1:2}
+            shift
+            set -- -"$first" -"$rest" "$@"
+            continue
+        ;;
         *)
             arguments+=("$1")
-            ;;
+        ;;
+    esac
+    shift
+done
 
-        esac
-        shift
-    done
+emojis=""
+if [  "${#type[@]}" -gt 0 ]; then
+    emojis="$(printf ":%s:" "${type[@]}")"
+fi
 
-    if [ -n "$type" ]; then
-        type=":$type: "
-    fi
+if [ "${#arguments[@]}" -lt 1 ]; then
+    echo "Error: missing arguments" >/dev/stderr
+    usage >/dev/stderr
+    exit 1
+fi
 
-    if [ "${#arguments[@]}" -lt 1 ]; then
-        echo "Error: missing arguments" >/dev/stderr
-        usage >/dev/stderr
-        exit 1
-    fi
-
-
-    git commit -m "${type}${arguments[*]}"
-
+argLine(){
+    printf "%s" "${emojis[*]}${arguments[*]}"
+}
+if "$preview"; then
+    echo $(argLine) 
+else
+    git commit -m "$(argLine)"
+fi
